"""Base strategy framework and data models."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import Enum

import pandas as pd

from src.core.config import MarketRegime


class StrategyType(str, Enum):
    """Strategy classification types."""

    TREND_FOLLOWING = "TREND_FOLLOWING"
    MEAN_REVERSION = "MEAN_REVERSION"
    BREAKOUT = "BREAKOUT"
    MOMENTUM = "MOMENTUM"


class TradingHorizon(str, Enum):
    """Trading time horizons."""

    INTRADAY = "INTRADAY"  # Close before market close
    SWING = "SWING"  # Hold overnight/multi-day
    BOTH = "BOTH"  # Can be either


class SignalDirection(str, Enum):
    """Signal direction."""

    LONG = "LONG"
    SHORT = "SHORT"
    HOLD = "HOLD"


@dataclass
class IndicatorSet:
    """Technical indicators for a specific timeframe."""

    timeframe: str  # e.g., "5m", "15m", "1h"
    sma_20: float | None = None
    ema_20: float | None = None
    rsi: float | None = None
    atr: float | None = None
    macd: float | None = None
    macd_signal: float | None = None
    macd_histogram: float | None = None
    bb_upper: float | None = None
    bb_middle: float | None = None
    bb_lower: float | None = None

    @property
    def is_complete(self) -> bool:
        """Check if all core indicators are present."""
        return all(
            [
                self.sma_20 is not None,
                self.ema_20 is not None,
                self.rsi is not None,
                self.atr is not None,
            ]
        )


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    symbol: str
    direction: SignalDirection
    strategy_name: str
    timeframe: str
    signal_strength: Decimal  # 0-100
    confidence: Decimal  # 0.0-1.0
    timestamp: datetime

    # Suggested levels
    suggested_entry: Decimal | None = None
    suggested_stop: Decimal | None = None
    suggested_target: Decimal | None = None

    # Context
    market_regime: MarketRegime | None = None
    horizon: TradingHorizon | None = None
    reasoning: str | None = None

    def __post_init__(self):
        """Validate signal values."""
        if not (0 <= self.signal_strength <= 100):
            raise ValueError(f"signal_strength must be 0-100, got {self.signal_strength}")
        if not (0 <= self.confidence <= 1):
            raise ValueError(f"confidence must be 0.0-1.0, got {self.confidence}")


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement:
    - analyze(): Generate signals based on market data
    - get_name(): Return strategy name
    - get_type(): Return strategy type
    - get_horizon(): Return trading horizon
    """

    def __init__(self, min_confidence: Decimal = Decimal("0.6")):
        """
        Initialize base strategy.

        Args:
            min_confidence: Minimum confidence threshold (0.0-1.0)
        """
        self.min_confidence = min_confidence

    @abstractmethod
    def get_name(self) -> str:
        """
        Get strategy name.

        Returns:
            Strategy name (e.g., "EMA_Crossover", "BollingerBands_MeanReversion")
        """
        pass

    @abstractmethod
    def get_type(self) -> StrategyType:
        """
        Get strategy classification type.

        Returns:
            Strategy type enum
        """
        pass

    @abstractmethod
    def get_horizon(self) -> TradingHorizon:
        """
        Get preferred trading horizon for this strategy.

        Returns:
            Trading horizon enum
        """
        pass

    @abstractmethod
    def analyze(
        self,
        symbol: str,
        bars: pd.DataFrame,
        indicators: dict[str, IndicatorSet],
        market_regime: MarketRegime,
        overrides: dict[str, str] | None = None,
    ) -> Signal | None:
        """
        Analyze market data and generate trading signal.

        Args:
            symbol: Stock symbol
            bars: DataFrame with recent OHLCV bars (primary timeframe)
            indicators: Dict mapping timeframe -> IndicatorSet
            market_regime: Current market regime
            overrides: Optional RLM strategy parameter overrides

        Returns:
            Signal object if valid signal generated, None otherwise
        """
        pass

    def is_regime_compatible(self, regime: MarketRegime) -> bool:
        """
        Check if current market regime is suitable for this strategy.

        Default implementation allows all regimes. Override if needed.

        Args:
            regime: Current market regime

        Returns:
            True if strategy works in this regime
        """
        return True

    def calculate_stop_loss(
        self,
        entry_price: Decimal,
        direction: SignalDirection,
        atr: Decimal,
        atr_multiple: Decimal = Decimal("2.0"),
    ) -> Decimal:
        """
        Calculate stop loss level based on ATR.

        Args:
            entry_price: Proposed entry price
            direction: Signal direction (LONG/SHORT)
            atr: Average True Range
            atr_multiple: ATR multiplier for stop distance

        Returns:
            Stop loss price
        """
        stop_distance = atr * atr_multiple

        if direction == SignalDirection.LONG:
            return entry_price - stop_distance
        else:  # SHORT
            return entry_price + stop_distance

    def calculate_take_profit(
        self,
        entry_price: Decimal,
        stop_loss: Decimal,
        direction: SignalDirection,
        reward_risk_ratio: Decimal = Decimal("2.0"),
    ) -> Decimal:
        """
        Calculate take profit level based on reward-risk ratio.

        Args:
            entry_price: Proposed entry price
            stop_loss: Stop loss price
            direction: Signal direction (LONG/SHORT)
            reward_risk_ratio: Target reward/risk ratio

        Returns:
            Take profit price
        """
        risk = abs(entry_price - stop_loss)
        reward = risk * reward_risk_ratio

        if direction == SignalDirection.LONG:
            return entry_price + reward
        else:  # SHORT
            return entry_price - reward

    def calculate_signal_strength(self, primary_score: float, confirmations: list[bool]) -> Decimal:
        """
        Calculate signal strength (0-100) based on primary score and confirmations.

        Args:
            primary_score: Primary indicator score (0-100)
            confirmations: List of boolean confirmations from other indicators

        Returns:
            Signal strength (0-100)
        """
        confirmation_weight = sum(confirmations) / len(confirmations) if confirmations else 0
        strength = (primary_score * 0.7) + (confirmation_weight * 100 * 0.3)
        return Decimal(str(round(strength, 2)))

    def calculate_confidence(
        self,
        signal_strength: Decimal,
        regime_compatible: bool,
        volume_confirmation: bool,
        multi_tf_agreement: bool,
    ) -> Decimal:
        """
        Calculate signal confidence (0.0-1.0) based on multiple factors.

        Args:
            signal_strength: Signal strength (0-100)
            regime_compatible: Is market regime compatible?
            volume_confirmation: Does volume support the signal?
            multi_tf_agreement: Do multiple timeframes agree?

        Returns:
            Confidence level (0.0-1.0)
        """
        # Base confidence from signal strength
        base_confidence = float(signal_strength) / 100.0

        # Adjust based on factors
        if regime_compatible:
            base_confidence += 0.1
        if volume_confirmation:
            base_confidence += 0.1
        if multi_tf_agreement:
            base_confidence += 0.15

        # Cap at 1.0
        confidence = min(base_confidence, 1.0)
        return Decimal(str(round(confidence, 2)))

    def __repr__(self) -> str:
        """String representation."""
        return f"<{self.get_name()} ({self.get_type().value}, {self.get_horizon().value})>"
