"""Order confirmation component for LIVE_CONFIRM mode."""

import asyncio
from datetime import datetime, timedelta

import streamlit as st

from dashboard.config import COLORS
from dashboard.utils.data_loader import load_pending_confirmations
from dashboard.utils.formatters import format_timestamp
from src.agents.execution_agent import ExecutionAgent
from src.core.config import AutomationMode, TradingConfig


def run_async(coro):
    """Run async coroutine in sync context."""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

    return loop.run_until_complete(coro)


@st.fragment(run_every=timedelta(seconds=5))
def render_order_confirmation():
    """Render pending order confirmations (LIVE_CONFIRM mode only)."""
    # Check if system is in LIVE_CONFIRM mode
    config = TradingConfig()

    if config.automation_mode != AutomationMode.LIVE_CONFIRM:
        # Don't show confirmation panel in other modes
        return

    st.subheader("⚠️ Pending Confirmations")

    # Load pending confirmations
    pending_df = load_pending_confirmations()

    if pending_df.empty:
        st.success("✓ No pending confirmations")
        return

    # Warning banner
    st.warning(
        f"**{len(pending_df)} order(s) awaiting confirmation!**\n\n"
        "These orders were generated by the trading system and require manual approval before execution."
    )

    # Display each pending order
    for idx, execution in pending_df.iterrows():
        with st.container():
            # Calculate time elapsed since confirmation request
            time_elapsed = datetime.now() - execution["confirmation_sent_at"]
            minutes_elapsed = int(time_elapsed.total_seconds() / 60)
            seconds_elapsed = int(time_elapsed.total_seconds() % 60)

            # Timeout warning (5 minutes)
            timeout_minutes = 5
            is_timeout_near = minutes_elapsed >= timeout_minutes - 1

            # Header
            col1, col2, col3 = st.columns([2, 2, 1])

            with col1:
                side_icon = "📈" if execution["side"] == "LONG" else "📉"
                side_color = COLORS["profit"] if execution["side"] == "LONG" else COLORS["loss"]

                st.markdown(
                    f"{side_icon} **{execution['symbol']}** :{side_color}[{execution['side']}]"
                )

            with col2:
                st.caption(f"Quantity: **{execution['qty']}** shares")

            with col3:
                if is_timeout_near:
                    st.markdown(f":red[⏱️ {minutes_elapsed}:{seconds_elapsed:02d}]")
                else:
                    st.caption(f"⏱️ {minutes_elapsed}:{seconds_elapsed:02d}")

            # Order details
            col1, col2 = st.columns(2)

            with col1:
                st.write("**Order Details**")
                st.write(f"Symbol: {execution['symbol']}")
                st.write(f"Side: {execution['side']}")
                st.write(f"Quantity: {execution['qty']} shares")

            with col2:
                st.write("**Timing**")
                st.write(f"Created: {format_timestamp(execution['created_at'])}")
                st.write(f"Elapsed: {minutes_elapsed}m {seconds_elapsed}s")

                if is_timeout_near:
                    st.error(f"⚠️ Timeout in {timeout_minutes - minutes_elapsed} minute(s)")

            st.divider()

            # Confirmation buttons
            col1, col2, col3 = st.columns([1, 1, 2])

            with col1:
                if st.button(
                    "✅ APPROVE",
                    key=f"approve_{execution['id']}",
                    type="primary",
                    use_container_width=True,
                ):
                    # Confirm execution
                    try:
                        execution_agent = ExecutionAgent(config, mode=AutomationMode.LIVE_CONFIRM)
                        success = run_async(
                            execution_agent.confirm_execution(
                                execution_id=execution["id"],
                                confirmed=True,
                                confirmed_by="DASHBOARD",
                            )
                        )

                        if success:
                            st.success(f"✓ Order {execution['id']} approved and submitted!")
                            st.rerun()
                        else:
                            st.error(f"Failed to approve order {execution['id']}")

                    except Exception as e:
                        st.error(f"Error approving order: {e}")

            with col2:
                if st.button(
                    "❌ REJECT",
                    key=f"reject_{execution['id']}",
                    use_container_width=True,
                ):
                    # Reject execution
                    try:
                        execution_agent = ExecutionAgent(config, mode=AutomationMode.LIVE_CONFIRM)
                        success = run_async(
                            execution_agent.confirm_execution(
                                execution_id=execution["id"],
                                confirmed=False,
                                confirmed_by="DASHBOARD",
                            )
                        )

                        if success:
                            st.info(f"Order {execution['id']} rejected")
                            st.rerun()
                        else:
                            st.error(f"Failed to reject order {execution['id']}")

                    except Exception as e:
                        st.error(f"Error rejecting order: {e}")

            with col3:
                st.caption(f"Execution ID: {execution['id']}")

            st.markdown("---")

    # Summary
    st.caption(f"**Total pending:** {len(pending_df)} order(s)")
