"""Phase 2 Recursive Learning Model ORM models."""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from src.core.database import Base


class LearningLog(Base):
    """
    Recursive Learning Model (RLM) predictions and reflections.

    Tracks predictions made by the system, actual outcomes, and LLM-based
    reflections for continuous improvement.
    """

    __tablename__ = "learning_logs"

    # Primary key
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # Foreign key to signals table
    signal_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("signals.id", ondelete="CASCADE"))

    # Signal metadata (denormalized for query performance)
    symbol: Mapped[str] = mapped_column(String(10), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    strategy_name: Mapped[str] = mapped_column(String(100), nullable=False)

    # === Prediction Phase ===
    predicted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    predicted_outcome: Mapped[str] = mapped_column(Text, nullable=False)
    predicted_target: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    prediction_horizon_mins: Mapped[int] = mapped_column(Integer, nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)

    # === Observation Phase ===
    observed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    actual_price: Mapped[Decimal | None] = mapped_column(Numeric(10, 2))
    actual_outcome: Mapped[str | None] = mapped_column(Text)
    prediction_correct: Mapped[bool | None] = mapped_column(Boolean)

    # === Reflection Phase (LLM Analysis) ===
    reflected_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    reflection_prompt: Mapped[str | None] = mapped_column(Text)
    reflection_response: Mapped[str | None] = mapped_column(Text)
    suggested_adjustment: Mapped[dict | None] = mapped_column(JSONB)
    adjustment_applied: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")

    # === Market Context ===
    market_regime: Mapped[str | None] = mapped_column(String(20))
    rsi_at_signal: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    atr_at_signal: Mapped[Decimal | None] = mapped_column(Numeric(10, 4))
    sentiment_score: Mapped[Decimal | None] = mapped_column(Numeric(5, 4))
    context_tag: Mapped[str | None] = mapped_column(String(50))

    # Relationships
    # signal = relationship("Signal", back_populates="learning_logs")

    def __repr__(self) -> str:
        return (
            f"<LearningLog(id={self.id}, symbol={self.symbol}, strategy={self.strategy_name}, "
            f"correct={self.prediction_correct})>"
        )


class StrategyOverride(Base):
    """
    Strategy configuration overrides generated by RLM.

    Stores dynamic adjustments to strategy parameters based on learning.
    Overrides expire automatically and can be manually reverted.
    """

    __tablename__ = "strategy_overrides"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Target strategy and parameter
    strategy_name: Mapped[str] = mapped_column(String(100), nullable=False)
    parameter_name: Mapped[str] = mapped_column(String(100), nullable=False)

    # Values
    original_value: Mapped[str | None] = mapped_column(String(100))
    override_value: Mapped[str] = mapped_column(String(100), nullable=False)

    # Metadata
    reason: Mapped[str | None] = mapped_column(Text)
    applied_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    reverted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Foreign key to learning_logs
    learning_log_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("learning_logs.id", ondelete="SET NULL")
    )

    # Relationships
    # learning_log = relationship("LearningLog", back_populates="strategy_overrides")

    def __repr__(self) -> str:
        status = "ACTIVE" if self.reverted_at is None and self.expires_at > datetime.now() else "EXPIRED"
        return (
            f"<StrategyOverride(strategy={self.strategy_name}, param={self.parameter_name}, "
            f"value={self.override_value}, status={status})>"
        )

    @property
    def is_active(self) -> bool:
        """Check if override is currently active."""
        return self.reverted_at is None and self.expires_at > datetime.now()


class ContextAnalysis(Base):
    """
    Market context analysis generated by ContextAgent (LLM).

    Caches sentiment analysis and regime classification from news/events.
    Used by StrategySelector to adjust thresholds and strategy selection.
    """

    __tablename__ = "context_analysis"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Symbol and timestamp
    symbol: Mapped[str] = mapped_column(String(10), nullable=False)
    analyzed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Analysis results
    sentiment_score: Mapped[Decimal] = mapped_column(
        Numeric(5, 4), nullable=False, comment="-1.0 (bearish) to +1.0 (bullish)"
    )
    regime_tag: Mapped[str] = mapped_column(
        String(50), nullable=False, comment="e.g., 'Geopolitical Risk', 'Supply Shock'"
    )
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 4), nullable=False, comment="0.0 to 1.0")
    reasoning: Mapped[str | None] = mapped_column(Text)

    # Input data (for debugging and audit)
    news_headlines: Mapped[dict | None] = mapped_column(JSONB)
    eia_events: Mapped[dict | None] = mapped_column(JSONB)
    market_metrics: Mapped[dict | None] = mapped_column(JSONB)

    # LLM interaction (for debugging)
    llm_prompt: Mapped[str | None] = mapped_column(Text)
    llm_response: Mapped[str | None] = mapped_column(Text)

    # Cache expiry
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    def __repr__(self) -> str:
        return (
            f"<ContextAnalysis(symbol={self.symbol}, sentiment={self.sentiment_score}, "
            f"regime={self.regime_tag}, confidence={self.confidence})>"
        )

    @property
    def is_expired(self) -> bool:
        """Check if analysis has expired."""
        return self.expires_at <= datetime.now()
