"""Trading signal ORM model."""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from src.core.database import Base


class Signal(Base):
    """Trading signals generated by strategy agents."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    symbol: Mapped[str] = mapped_column(String(10), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)  # LONG, SHORT
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(5), nullable=False)

    # Signal strength and confidence
    signal_strength: Mapped[Decimal] = mapped_column(
        Numeric(5, 2), nullable=False, comment="0.0 to 100.0"
    )
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False, comment="0.0 to 1.0")

    # Suggested entry and exit levels
    suggested_entry: Mapped[Decimal | None] = mapped_column(Numeric(10, 4))
    suggested_stop: Mapped[Decimal | None] = mapped_column(Numeric(10, 4))
    suggested_target: Mapped[Decimal | None] = mapped_column(Numeric(10, 4))

    # Market context
    market_regime: Mapped[str | None] = mapped_column(
        String(20), comment="TRENDING, RANGING, VOLATILE"
    )
    horizon: Mapped[str | None] = mapped_column(String(10), comment="INTRADAY, SWING, BOTH")

    # Reasoning (JSON or text)
    reasoning: Mapped[str | None] = mapped_column(Text)

    # Phase 2: Execution tracking
    executed: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    execution_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("executions.id", ondelete="SET NULL")
    )

    # Relationships
    # execution = relationship("Execution", back_populates="signals")
    # learning_logs = relationship("LearningLog", back_populates="signal")

    def __repr__(self) -> str:
        return (
            f"<Signal(symbol={self.symbol}, direction={self.direction}, "
            f"strategy={self.strategy_name}, strength={self.signal_strength}, "
            f"executed={self.executed})>"
        )
